"""Initial migration

Revision ID: 56ddbeae1bd
Revises: None
Create Date: 2014-09-10 15:53:41.345983

"""

# revision identifiers, used by Alembic.
revision = '56ddbeae1bd'
down_revision = None

from alembic import op
import sqlalchemy as sa

from application import db
from application.models import User

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.Column('username', sa.String(length=80), nullable=False),
      sa.Column('password', sa.String(), nullable=False),
      sa.Column('email', sa.String(length=120), nullable=False),
      sa.PrimaryKeyConstraint('id'),
      sa.UniqueConstraint('email'),
      sa.UniqueConstraint('username')
    )
    op.create_table('analogues',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.Column('user_id', sa.Integer(), nullable=False),
      sa.Column('name', sa.String(), nullable=False),
      sa.Column('description', sa.UnicodeText(), nullable=True),
      sa.Column('author', sa.String(), nullable=True),
      sa.Column('DOI', sa.String(), nullable=True),
      sa.Column('pub_date', sa.Date(), nullable=True),
      sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
      sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectra',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.Column('analogue_id', sa.Integer(), nullable=False),
      sa.Column('temperature', sa.Float(), nullable=False),
      sa.Column('resolution', sa.Float(), nullable=True),
      sa.Column('description', sa.UnicodeText(), nullable=True),
      sa.Column('path', sa.String(), nullable=False),
      sa.ForeignKeyConstraint(['analogue_id'], ['analogues.id'], ),
      sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spectra')
    op.drop_table('analogues')
    op.drop_table('users')
    ### end Alembic commands ###
